dist: xenial   # required for Python >= 3.7
language: python
# python versions to use during the tests
python:
  - "3.7"
# command to install dependencies
#before_install:
#  - sudo apt-get install xclip xsel    # should satisfy copy/paste mechanism requirement
install:
  - pip install -r requirements.txt
script:
  - pytest -ra -v
notifications:
  email:
    recipients:
      - localhost@zspatter.dev
    on_success: change
    on_failure: always
